[package]
name = "cli_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib","rlib","staticlib"]

[dependencies]
colored = "2.0"
thiserror = "1.0"
lazy_static = "1.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
once_cell = "1.8"
rpassword = "5.0"